name: "ceshi"
on:
  push:
    branches:
      - master


jobs:
  hello:
    name: "hello"
    runs-on: ubuntu-latest
    steps:
      - name: 'zs'
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script:
            whoami
            cd /www/apk
            git clone  https://github.com/jiatingyu/yibei-express-jkgl.git
            cd ./yibei-express-jkgl
            yarn build
            yarn start
             
