name: "测试发布"
on:
  push:
    branches:
      - master


jobs:
  hello:
    name: "deploy"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: 'connect linux'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            node -v
            cd /
            ls -al
            
      - name: "serve"
        run: |
            cd /www/apk/
            git clone https://github.com/jiatingyu/yibei-express-jkgl.git
            cd ./yibei-express-jkgl
            npm install
            npm run build
            npm run start
