name: "ceshi"
on:
  push:
    branches:
      - master


jobs:
  hello:
    name: "hello"
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@master
      - name: 'zs'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script:
            node -v
            cd /www/apk
            git clone https://github.com/jiatingyu/yibei-express-jkgl.git
            cd ./yibei-express-jkgl
            npm install 
            npm run build
            npm run start
             
