name: "测试发布"
on:
  push:
    branches:
      - master


jobs:
  hello:
    name: "deploy"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: 'connect linux'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            node -v
            rm -rf /www/apk/yibei-express-jkgl
            cd /www/apk/
            git clone https://github.com/jiatingyu/yibei-express-jkgl.git
            cd /www/apk/yibei-express-jkgl
            npm install
            npm run build
            npm run start
      - name: '测试位置'
        run: | 
          uname -a 
          ls -al
